name = "hono_tododb"
compatibility_date = "2023-12-01"

[vars]
MONGODB_DATABASE_URL="mongodb+srv://kaushiksahu18:Q9zcaZ20nw4058yA@cluster0.4gfxqbo.mongodb.net/"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"